# ARRAYS

pip3 install array

type conda promp


In [1]:
import array as arr

In [2]:
a=arr.array('i',[1,2,3,4,5])
b=arr.array('d',[1.2,4.0,5.9,8.9])

In [3]:
b

array('d', [1.2, 4.0, 5.9, 8.9])

In [4]:
a

array('i', [1, 2, 3, 4, 5])

In [5]:
len(a)

5

In [6]:
len(b)

4

In [7]:
a[3]

4

In [10]:
b[2]

5.9

In [9]:
b[1]

4.0

In [11]:
a.append(34)

In [12]:
a

array('i', [1, 2, 3, 4, 5, 34])

In [13]:
a.append(11)

In [14]:
a

array('i', [1, 2, 3, 4, 5, 34, 11])

In [15]:
a.remove(5)

In [16]:
a

array('i', [1, 2, 3, 4, 34, 11])

In [17]:
len(a)

6

In [18]:
b.append(15)

In [19]:
b

array('d', [1.2, 4.0, 5.9, 8.9, 15.0])

In [20]:
b.remove(1.2)

In [21]:
b

array('d', [4.0, 5.9, 8.9, 15.0])

In [22]:
b[3]

15.0

In [23]:
a[1]

2

In [24]:
a.pop(2)

3

In [25]:
a

array('i', [1, 2, 4, 34, 11])

In [27]:
a.append(54)

In [28]:
a

array('i', [1, 2, 4, 34, 11, 54])

In [29]:
a[::1]

array('i', [1, 2, 4, 34, 11, 54])

In [30]:
a[::-1]

array('i', [54, 11, 34, 4, 2, 1])

In [31]:
b[::1]

array('d', [4.0, 5.9, 8.9, 15.0])

In [32]:
b[::-1]

array('d', [15.0, 8.9, 5.9, 4.0])

In [33]:
a.index(2)

1

In [35]:
a.index(1)

0

In [36]:
b.index(4)

0

In [43]:
a.insert(3,22)

In [44]:
a

array('i', [1, 2, 4, 22, 34, 11, 54])

In [45]:
b.insert(4,7)

In [46]:
b

array('d', [4.0, 5.9, 8.9, 15.0, 7.0])

In [47]:
c=arr.array('i',[3,5,9,0,45])

In [49]:
a+c

array('i', [1, 2, 4, 22, 34, 11, 54, 3, 5, 9, 0, 45])

In [51]:
d=arr.array('d',[2.5,4,5,6.9])

In [52]:
b+d

array('d', [4.0, 5.9, 8.9, 15.0, 7.0, 2.5, 4.0, 5.0, 6.9])

# NUMPYS

pip3 install numpy

In [53]:
import numpy as np

In [54]:
a=np.array([[1,1,3],[5,2,6],[8,7,9]])

In [55]:
a

array([[1, 1, 3],
       [5, 2, 6],
       [8, 7, 9]])

In [56]:
b=np.array([[7,4,6],[7,2,1],[42,2,5]])

In [57]:
b

array([[ 7,  4,  6],
       [ 7,  2,  1],
       [42,  2,  5]])

In [58]:
a.dtype

dtype('int32')

In [59]:
b.dtype

dtype('int32')

In [60]:
a.size

9

In [61]:
b.size

9

In [62]:
a[:3]

array([[1, 1, 3],
       [5, 2, 6],
       [8, 7, 9]])

In [63]:
a[:1]

array([[1, 1, 3]])

In [64]:
a[:-1]

array([[1, 1, 3],
       [5, 2, 6]])

In [65]:
b[:-2]

array([[7, 4, 6]])

In [66]:
a-b

array([[ -6,  -3,  -3],
       [ -2,   0,   5],
       [-34,   5,   4]])

In [67]:
a+b

array([[ 8,  5,  9],
       [12,  4,  7],
       [50,  9, 14]])

In [68]:
a*b

array([[  7,   4,  18],
       [ 35,   4,   6],
       [336,  14,  45]])

In [69]:
a/b

array([[0.14285714, 0.25      , 0.5       ],
       [0.71428571, 1.        , 6.        ],
       [0.19047619, 3.5       , 1.8       ]])

In [70]:
type(b)

numpy.ndarray

In [71]:
type(a)

numpy.ndarray

In [72]:
a.ndim

2

In [76]:
b.shape

(3, 3)

In [77]:
a.shape

(3, 3)

In [78]:
c=np.zeros((4,4))

In [79]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
d=np.array([[2,4,1],[7,5,4]],dtype ='float')

In [81]:
d

array([[2., 4., 1.],
       [7., 5., 4.]])

In [82]:
a.max()

9

In [83]:
b.min()

1

In [84]:
a.min()

1

In [85]:
a.max(axis=1)

array([3, 6, 9])

In [86]:
a.sum()

42

In [87]:
b.sum()

76

In [88]:
a.sort(axis=1)

In [89]:
a

array([[1, 1, 3],
       [2, 5, 6],
       [7, 8, 9]])

In [90]:
np.diag(a)

array([1, 5, 9])

In [91]:
np.diag(b)

array([7, 2, 5])

In [92]:
np.sqrt(a)

array([[1.        , 1.        , 1.73205081],
       [1.41421356, 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [93]:
np.sqrt(b)

array([[2.64575131, 2.        , 2.44948974],
       [2.64575131, 1.41421356, 1.        ],
       [6.4807407 , 1.41421356, 2.23606798]])

In [94]:
np.trace(a)

15

In [95]:
np.trace(b)

14

In [97]:
a+b

array([[ 8,  5,  9],
       [ 9,  7,  7],
       [49, 10, 14]])

In [98]:
c.max()

0.0

In [99]:
d.max()

7.0

In [100]:
d.min()

1.0

In [101]:
c.min()

0.0